#! /bin/bash

export AWS_REGION=cn-north-1
export AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
PGBOUNCER_VERSION="1.14.0"
readonly PGBOUNCER_VERSION

AIRFLOW_PGBOUNCER_VERSION="2021.04.28"
readonly AIRFLOW_PGBOUNCER_VERSION

docker build . --build-arg "PGBOUNCER_VERSION=${PGBOUNCER_VERSION}" \
    --build-arg "AIRFLOW_PGBOUNCER_VERSION=${AIRFLOW_PGBOUNCER_VERSION}" \
    -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com.cn/apache/airflow:airflow-pgbouncer-2021.04.28-1.14.0-arm64
